- id: sbt-scalafmt
  name: Scala formatting
  stages: [commit,push]
  language: python_venv
  entry: sbt
  args: ['scalafmt']
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '0.19.0'
- id: sbt-scalafix
  name: Scala Fix remove unused imports
  language: python_venv
  stages: [commit,push]
  entry: sbt
  args: ['"scalafix RemoveUnused"']
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '0.19.0'